org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=1024m -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
org.gradle.daemon=true
org.gradle.parallel=true
kotlin.incremental=false
kotlin.compiler.execution.strategy=in-process
android.useAndroidX=true
android.enableJetifier=true

# Add this line to force Gradle to use Java 21
org.gradle.java.home=C:/Program Files/Android/Android Studio/jbr
