// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:            
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiq2f5HKqj0_M4jVWxUxFjl8czqN3V_g0',
    appId: '1:856962329109:ios:3d24c9af8bae4d79233c1c',
    messagingSenderId: '856962329109',
    projectId: 'areebakhan-transport',
    storageBucket: 'areebakhan-transport.firebasestorage.app',
    iosBundleId: 'com.areebakhan.transportApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiq2f5HKqj0_M4jVWxUxFjl8czqN3V_g0',
    appId: '1:856962329109:ios:3d24c9af8bae4d79233c1c',
    messagingSenderId: '856962329109',
    projectId: 'areebakhan-transport',
    storageBucket: 'areebakhan-transport.firebasestorage.app',
    iosBundleId: 'com.areebakhan.transportApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5WKSY9BlCgFAHi53GLENl-TRg5SQvTu0',
    appId: '1:856962329109:web:c47876cb96c29429233c1c',
    messagingSenderId: '856962329109',
    projectId: 'areebakhan-transport',
    authDomain: 'areebakhan-transport.firebaseapp.com',
    storageBucket: 'areebakhan-transport.firebasestorage.app',
    measurementId: 'G-EJD6PRBQ83',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5WKSY9BlCgFAHi53GLENl-TRg5SQvTu0',
    appId: '1:856962329109:web:c47876cb96c29429233c1c',
    messagingSenderId: '856962329109',
    projectId: 'areebakhan-transport',
    authDomain: 'areebakhan-transport.firebaseapp.com',
    storageBucket: 'areebakhan-transport.firebasestorage.app',
    measurementId: 'G-EJD6PRBQ83',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSZNt-9W_uNzBDx4Nd9ZnL1MSvjxnyoKQ',
    appId: '1:856962329109:android:278d2133ee6cb760233c1c',
    messagingSenderId: '856962329109',
    projectId: 'areebakhan-transport',
    storageBucket: 'areebakhan-transport.firebasestorage.app',
  );

}